Публикация
htmlacademy-yii/243436-task-force-1 pull request #15
Opened 2021-07-26 16:27 UTC by Pavel357

Публикация

2021-07-27 02:16 UTC, b1rdex requested changes

2021-07-27 02:16 UTC, b1rdex commented on frontend/controllers/CreateController.php
> +        \Yii::$app->user->loginUrl = ['landing/index'];
Это можно вынести в конфиг

2021-07-27 02:16 UTC, b1rdex commented on console/migrations/m210723_073126_create_tasks_and_clips_table.php
> +        $this->createTable('{{%tasks_and_clips}}', [
Похоже миграция не та. Вместо таблицы tasks_and_clips ты добавил поле task_id в модели Clips

2021-07-27 02:16 UTC, b1rdex commented on frontend/controllers/CreateController.php
> +                            return \Yii::$app->user->identity->role != 'Заказчик';
Я бы лучше наследовался от SecureController и в самом экшне сделал маленький `if (Yii::$app->user->identity->role != 'Заказчик') { throw new \yii\web\ForbiddenHttpException(); }`, т.к. в таком виде получается очень громоздко. Это не критично, можно не переделывать.

2021-07-27 02:16 UTC, b1rdex commented on frontend/controllers/CreateController.php
> +                $task_id = \Yii::$app->db->getLastInsertID();
```suggestion
                $task_id = $tasks_form->id;
```

2021-07-27 02:16 UTC, b1rdex commented on frontend/controllers/CreateController.php
> +                $tasks_form->upload($task_id);
Ну и в целом можно это вызывать автоматически, если добавить в Tasks метод afterSave :)
Это не обязательно, можно не переделывать.

2021-07-27 02:16 UTC, b1rdex commented on frontend/models/Tasks.php
> +                $newname = $file->baseName . '.' . $file->getExtension();
По-хорошему, нужно файлу генерировать случайное имя, т.к. сейчас есть возможность перезаписать файл в случае сопадения имён. Можно либо полностью генерировать уникальное имя, либо добавить к оригинальному имени:
```suggestion
                $newname = $file->baseName . '.' . uniqid('', true) . '.' . $file->getExtension();
```

2021-07-27 04:16 UTC, Pavel357 commented on console/migrations/m210723_073126_create_tasks_and_clips_table.php
> +        $this->createTable('{{%tasks_and_clips}}', [
Это я экспериментировал, поле  task_id уже было

2021-07-29 01:44 UTC, b1rdex requested changes
Ещё нужно удалить файлы из папки frontend/web/uploads/
И добавить её в .gitignore, чтобы загрузки не попадали в репозиторий

2021-07-29 01:44 UTC, b1rdex commented on frontend/controllers/CreateController.php
> +                foreach($session['images'] as $image) {
Тут не может быть ошибки если в сессии не будет такого ключа?

2021-07-29 01:44 UTC, b1rdex commented on frontend/controllers/CreateController.php
> +                }
После цикла нужно очистить $session['images'], т.к. данные уже использованы

2021-07-29 01:44 UTC, b1rdex commented on frontend/controllers/CreateController.php
> +            \Yii::$app->session['images'] = $images;
В текущем виде у тебя сохранятся картинки только с последней загрузки, т.к. ты перезаписываешь ключ. Можно вместо `$images = []` в начале метода сделать `$images = Yii::$app->session['images'] ?? []`

2021-07-29 01:44 UTC, b1rdex commented on frontend/web/file.txt
> +Array
Это удалить

2021-08-01 08:19 UTC, b1rdex approved these changes

2021-08-01 08:19 UTC, merged